#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOLS_RS = ROOT / "src" / "tools.rs"
README = ROOT / "README.md"


def catalog_names() -> list[str]:
    lines = TOOLS_RS.read_text(encoding="utf-8").splitlines()
    names: list[str] = []
    for i, line in enumerate(lines):
        if "#[tool(" not in line:
            continue
        for j in range(i, min(i + 25, len(lines))):
            m = re.match(r"\s*async fn (\w+)", lines[j])
            if m:
                names.append(m.group(1))
                break
    return names


CATEGORIES: dict[str, list[str]] = {
    "Listing / metadata": [
        "list_scripts",
        "list_classes",
        "list_segments",
        "list_imports",
        "list_exports",
        "list_namespaces",
        "list_data_items",
        "search_functions_by_name",
        "get_function_by_address",
        "get_current_address",
        "get_current_function",
        "list_functions",
        "list_sections_detailed",
        "detect_protector",
        "analyze_virtualization",
        "obfuscation_profile",
        "detect_security_mitigations",
        "list_tls_callbacks",
        "tls_singleton_map",
        "derive_tls_singletons",
        "prove_offset",
        "address_context",
        "reachability",
        "nebula_shape",
        "nebula_container_layout",
        "nebula_assert_helpers",
        "nebula_engine_survey",
        "nebula_bootstrap",
        "seed_nebula_helpers",
        "name_from_n_assert",
        "name_from_signatures",
        "list_nebula_instances",
        "name_nebula_instances",
        "factory_catalog",
        "nebula_class_graph",
        "assert_catalog",
        "messaging_catalog",
        "attr_catalog",
        "source_tree",
        "funcsig_graph",
        "raknet_packet_lookup",
        "assemble_code",
        "extract_api_call_sequences",
        "vm_descriptor_table",
        "list_entry_points",
        "program_info",
        "program_metadata",
        "function_stack_frame",
        "list_strings",
        "list_relocations",
        "list_bookmarks",
        "extract_iocs",
        "find_rop_gadgets",
        "find_format_string_vulns",
        "export_offsets",
    ],
    "Decompile / disasm": [
        "decompile",
        "disassemble_function",
        "instruction_at",
        "pcode_function",
    ],
    "Xrefs / CFG / diff": [
        "xrefs",
        "list_callers",
        "list_callees",
        "basic_blocks",
        "function_string_refs",
        "callgraph",
        "function_cfg",
        "cfg_metrics",
        "dominator_tree",
        "xref_graph",
        "namespace_graph",
        "struct_diagram",
        "taint_forward",
        "taint_backward",
        "diff_functions",
        "diff_programs",
        "propagate_matches",
        "function_summary_bundle",
        "function_field_writes",
        "function_hash",
    ],
    "Bytes / patching / IO": [
        "read_bytes",
        "search",
        "patch_bytes",
        "hex_dump",
        "nop_range",
        "export_binary",
        "write_artifact",
        "save_program",
        "xor_decrypt",
        "import_memory_dump",
        "create_label",
    ],
    "Rename / types / batch edit": [
        "rename",
        "set_decompiler_comment",
        "set_disassembly_comment",
        "set_function_prototype",
        "set_local_variable_type",
        "import_c_header",
        "demangle_symbol",
        "demangle_all",
        "create_struct",
        "create_union",
        "create_enum",
        "batch_rename",
        "batch_set_comment",
        "batch_set_prototype",
        "batch_set_variable_type",
        "set_variables",
        "apply_naming_convention",
    ],
    "Type recovery / analysis control": [
        "analyze_program",
        "list_analyzers",
        "set_analysis_option",
        "apply_data_type",
        "batch_apply_data_type",
        "create_function",
        "propagate_function_types",
        "recover_rtti_classes",
        "list_data_type_archives",
        "apply_gdt",
        "import_dwarf",
        "import_pdb",
        "apply_fid_signatures",
        "propose_struct_from_accesses",
        "list_open_programs",
        "select_program",
        "struct_field",
    ],
    "Self-driving RE / discovery": [
        "function_completeness",
        "find_undocumented",
        "ghidra_eval",
        "live_probe_snippets",
        "refine_function",
        "analysis_note",
        "analysis_notes",
        "search_tools",
        "get_tool_schema",
    ],
    "Signatures / malware triage": [
        "find_encoded_strings",
        "recover_hidden_strings",
        "recover_auth_surface",
        "function_behavior",
        "sample_intake",
        "capability_map",
        "recover_crypto_recipe",
        "find_secret_compares",
        "export_yara",
        "decode_keystream",
        "pe_facts",
        "find_hash_blobs",
        "find_self_modify",
        "find_api_hashes",
        "find_stack_strings",
        "high_entropy_regions",
        "find_anti_debug",
        "find_orphan_gaps",
        "vtable_scan",
        "find_check_function",
        "extract_constraints",
        "simplify_expression",
        "find_opaque_predicates",
        "find_magic_constants",
        "neutralize_anti_debug",
        "idiom_simplifier",
        "make_signature",
        "resolve_relative",
        "find_crypto_constants",
        "find_syscalls",
        "find_anti_vm",
        "cfg_obfuscation_score",
        "unpack_assist",
        "coverage",
        "decode_strings_auto",
        "find_dynamic_api_resolution",
        "find_function_by_string",
        "emulate",
    ],
    "Emulation sessions": [
        "emulate_function",
        "recover_decoded_strings",
        "emu_start",
        "emu_session",
    ],
    "Debugger": [
        "debugger_status",
        "debugger_list_targets",
        "debugger_list_modules",
        "debugger_threads",
        "debugger_stack_trace",
        "debugger_registers",
        "debugger_read_memory",
        "debugger_list_breakpoints",
        "debugger_set_breakpoint",
        "debugger_remove_breakpoint",
        "debugger_continue",
        "debugger_step_into",
        "debugger_step_over",
        "debugger_break",
        "debugger_list_offers",
        "debugger_backend_log",
        "debugger_launch",
        "debugger_detach",
        "debugger_translate_static_to_dynamic",
        "debugger_translate_dynamic_to_static",
    ],
    "Live process": [
        "live_processes",
        "live_attach",
        "live_release",
        "live_modules",
        "live_threads",
        "lua_find_state",
        "lua_exec",
        "freeze",
        "scan",
        "read_pointer_path",
        "live_read_struct",
        "live_probe",
        "pointer_scan",
        "live_write_memory",
        "live_write_register",
    ],
}

PURPOSES: dict[str, str] = {
    "list_scripts": "available Ghidra scripts (.java/.py)",
    "list_classes": "namespace classes",
    "decompile": "C pseudocode (clean=true casts; clean=std drops std::string noise)",
    "rename": "rename function / data / variable (kind=…)",
    "list_segments": "memory segments",
    "list_imports": "imported symbols (with IAT VA)",
    "list_exports": "exported symbols",
    "list_namespaces": "namespaces",
    "list_data_items": "defined data",
    "search_functions_by_name": "substring match on function names",
    "get_function_by_address": "resolve function by address",
    "get_current_address": "cursor address",
    "get_current_function": "function at cursor",
    "list_functions": "functions (with_address name+addr or names-only)",
    "disassemble_function": "raw assembly for a function",
    "set_decompiler_comment": "PRE / plate comment",
    "set_disassembly_comment": "EOL comment",
    "set_function_prototype": "set full function prototype",
    "set_local_variable_type": "retype a local variable",
    "xrefs": "references (direction=both|to|from)",
    "taint_forward": "forward data-flow slice",
    "taint_backward": "backward data-flow slice",
    "diff_functions": "structural/semantic compare or dual decompile",
    "diff_programs": "whole-program function matching by shape hash",
    "propagate_matches": "copy names onto matches in another open program",
    "list_callers": "direct callers",
    "list_callees": "direct callees",
    "basic_blocks": "CFG basic blocks",
    "read_bytes": "raw hex bytes",
    "search": "kind=bytes|string|signature (bytes is cursor-resumable)",
    "patch_bytes": "write hex (optional re-disassembly)",
    "hex_dump": "formatted hex dump",
    "function_string_refs": "strings referenced by a function",
    "instruction_at": "single instruction at address",
    "nop_range": "patch range with NOPs",
    "export_binary": "dump program bytes",
    "write_artifact": "write allow-listed UTF-8 artifact under File IO Directory",
    "save_program": "persist renames/comments/patches",
    "xor_decrypt": "XOR a memory range",
    "import_memory_dump": "load bytes from file into memory",
    "find_encoded_strings": "xor-encoded string blobs",
    "recover_hidden_strings": "SplitMix64 / rolling-XOR / MOV-imm string decrypt",
    "recover_auth_surface": "license/C2/HWID/crypto surface in one call",
    "function_behavior": "compact malware function card (tags+APIs+hidden strings)",
    "sample_intake": "one-call PE + packer + capa + optional hidden strings",
    "capability_map": "capa-style inject/C2/crypto/anti-debug/HWID/license map",
    "recover_crypto_recipe": "BCrypt/WinCrypt call-order recipes (AES-GCM/HMAC)",
    "find_secret_compares": "strcmp/memcmp/license-string/fat-immediate compares",
    "export_yara": "YARA rule from hosts, /api/ paths, GUIDs, mutexes",
    "decode_keystream": "apply SplitMix/rolling-XOR seed to a ciphertext range",
    "pe_facts": "PE timestamp, subsystem, admin manifest, PDB",
    "find_hash_blobs": "defined MD5/SHA-1/SHA-256-sized constant blobs",
    "find_self_modify": "VirtualProtect+WriteProcessMemory unpack/hook sites",
    "find_api_hashes": "resolve hashed imports",
    "find_stack_strings": "stack-built strings",
    "emulate": "one-shot p-code emulation",
    "emulate_function": "emulate one function with args; read return",
    "recover_decoded_strings": "emulate a decoder; harvest produced strings",
    "emu_start": "start persistent p-code emulator session",
    "emu_session": "drive session (step/run_to/regs/setreg/read/write/close)",
    "high_entropy_regions": "packed/encrypted high-entropy zones",
    "create_label": "add a label",
    "list_sections_detailed": "sections + RWX + entropy",
    "detect_protector": "packer/protector indicators",
    "analyze_virtualization": "VM/engine entry points + reverse calls",
    "obfuscation_profile": "one-call obfuscation verdict",
    "detect_security_mitigations": "PE hardening (ASLR/DEP/CFG/SafeSEH/GS)",
    "list_tls_callbacks": "PE TLS callbacks",
    "tls_singleton_map": "TLS slot map (+ live ptrs after live_attach)",
    "derive_tls_singletons": "derive TLS slots from \"0 != Singleton\" asserts",
    "prove_offset": "prove a field offset from the n_assert that names it",
    "factory_catalog": "Core::Factory / Rtti class + FourCC + BSS catalog",
    "nebula_class_graph": "class hierarchy + sizeof from Core::Rtti::Construct",
    "assert_catalog": "this-> n_assert field index (optional prove)",
    "messaging_catalog": "Messaging:: classes + HandleMessage dispatchers",
    "attr_catalog": "Attr names and money_* wallets",
    "source_tree": "functions grouped by embedded .cc/.h path",
    "funcsig_graph": "C++ namespace graph from __cdecl signature strings",
    "address_context": "function start? mid-instruction? unshifted bytes",
    "reachability": "dead vs live, ignoring self .pdata; CRT inits are live",
    "nebula_shape": "proven container geometry + cross-check vs code",
    "nebula_container_layout": "container layout recovery from decompile",
    "nebula_assert_helpers": "locate n_assert / n_error / n_warning helpers",
    "nebula_engine_survey": "Nebula3 readiness: auto-names + assert callers",
    "nebula_bootstrap": "run the whole recovery chain in one call",
    "seed_nebula_helpers": "auto-discover/name n_assert/n_error/n_warning",
    "name_from_n_assert": "mass-name FUN_* (sigs or decompile modes)",
    "name_from_signatures": "fast name from __cdecl signature string xrefs",
    "list_nebula_instances": "list ::Instance() singleton signature sites",
    "name_nebula_instances": "rename auto FUN_* that are Type::Instance()",
    "raknet_packet_lookup": "DSO RakNet packet id → name/notes/handler",
    "assemble_code": "assemble asm text to bytes",
    "extract_api_call_sequences": "ordered API-call trace of a function",
    "vm_descriptor_table": "virtualizer dispatch table map",
    "list_entry_points": "entry points",
    "find_anti_debug": "known anti-debug APIs",
    "program_info": "language, arch, base, sha256",
    "program_metadata": "full metadata map",
    "function_stack_frame": "stack variables for a function",
    "import_c_header": "parse C header into types",
    "demangle_symbol": "demangle one C++ symbol",
    "demangle_all": "demangle + rename all",
    "create_struct": "new StructureDataType",
    "create_union": "new UnionDataType",
    "create_enum": "new EnumDataType",
    "pcode_function": "raw p-code per instruction",
    "callgraph": "call graph (mermaid|dot)",
    "function_cfg": "Mermaid CFG for one function",
    "cfg_metrics": "block/edge/cyclomatic/loop complexity",
    "dominator_tree": "immediate dominators of basic blocks",
    "xref_graph": "one-hop reference graph (mermaid|html)",
    "namespace_graph": "Mermaid namespace/class hierarchy",
    "struct_diagram": "Mermaid classDiagram of a struct",
    "find_orphan_gaps": "code outside any function",
    "vtable_scan": "heuristic vtable finder",
    "list_strings": "defined strings (optional regex + xrefs)",
    "list_relocations": "relocation entries",
    "list_bookmarks": "analysis bookmarks",
    "debugger_status": "trace/target state",
    "debugger_list_targets": "debug targets",
    "debugger_list_modules": "loaded modules",
    "debugger_threads": "live threads",
    "debugger_stack_trace": "call stack of a thread",
    "debugger_registers": "frame registers",
    "debugger_read_memory": "live target memory",
    "read_pointer_path": "resolve multi-level pointer chain",
    "live_read_struct": "read typed live-memory fields from a schema",
    "live_probe": "named persistent live reads (define/run/list)",
    "pointer_scan": "reverse-scan image for pointers into a target",
    "debugger_list_breakpoints": "logical breakpoints",
    "debugger_set_breakpoint": "set breakpoint",
    "debugger_remove_breakpoint": "remove breakpoint",
    "debugger_continue": "resume target",
    "debugger_step_into": "step into",
    "debugger_step_over": "step over",
    "debugger_break": "interrupt target",
    "live_write_memory": "write live process memory",
    "live_write_register": "write live register",
    "debugger_list_offers": "available launchers/connectors",
    "debugger_backend_log": "recent debugger backend log lines",
    "debugger_launch": "launch/attach from MCP",
    "debugger_detach": "detach without killing",
    "live_processes": "enumerate running processes",
    "live_attach": "connector-less attach by name/pid",
    "live_release": "release live anchor (process untouched)",
    "live_modules": "modules of attached process",
    "live_threads": "threads of attached process",
    "lua_find_state": "auto-detect embedded Lua 5.1 lua_State",
    "lua_exec": "run Lua inside live embedded VM (override hook/fn defaults per target)",
    "ghidra_eval": "run Java/Python with full Ghidra API (+ live helpers)",
    "live_probe_snippets": "reusable Java snippets for live probes",
    "analysis_note": "record a freeform analysis note",
    "analysis_notes": "list recorded analysis notes",
    "refine_function": "re-analyze + retype one function; report delta",
    "freeze": "hold/release a live value (op=on|off|list)",
    "scan": "live memory scan session (op=first|next|results|close)",
    "debugger_translate_static_to_dynamic": "static address to live",
    "debugger_translate_dynamic_to_static": "live address to static",
    "find_check_function": "crackme check-function locator",
    "extract_constraints": "cmp/branch constraints",
    "simplify_expression": "recover linear-MBA normal form",
    "find_opaque_predicates": "always-true/false conditional branches",
    "find_magic_constants": "magic immediates (incl. SplitMix64 string-xor mixers)",
    "neutralize_anti_debug": "patch anti-debug calls to return 0",
    "idiom_simplifier": "annotate arithmetic idioms",
    "make_signature": "unique wildcarded AOB signature",
    "resolve_relative": "resolve call/jmp/RIP-relative targets",
    "batch_rename": "many renames, one transaction",
    "batch_set_comment": "many comments, one transaction",
    "function_summary_bundle": "decompile + callers + callees + strings (+ API trace)",
    "function_field_writes": "field/vtable-write summary + strings",
    "batch_set_prototype": "many prototypes, one transaction",
    "batch_set_variable_type": "many local retypes, one transaction",
    "function_completeness": "score one function 0-100 with breakdown",
    "find_undocumented": "functions ranked least-documented first",
    "find_crypto_constants": "AES/SHA/MD5/CRC constant tables",
    "extract_iocs": "URLs/IPs/emails/registry/paths/GUIDs/wallets (/api, JWT; scope=raw|both)",
    "find_rop_gadgets": "ROP gadgets (ret-terminated)",
    "find_format_string_vulns": "printf-family non-constant format (CWE-134)",
    "find_syscalls": "syscall/sysenter/int 2e stubs + SSN",
    "find_anti_vm": "VM/sandbox artifact strings",
    "cfg_obfuscation_score": "CFG-flattening / obfuscation score",
    "unpack_assist": "packer/protector detection score",
    "coverage": "coverage report / from_trace / diff",
    "decode_strings_auto": "brute-force XOR/ADD/SUB string decode",
    "function_hash": "structural or semantic function hash",
    "recover_rtti_classes": "C++ classes + vftable + method count",
    "find_dynamic_api_resolution": "GetProcAddress/LoadLibrary call sites",
    "list_data_type_archives": "program/builtin/GDT type archives",
    "apply_gdt": "merge a .gdt archive (sandboxed path)",
    "import_dwarf": "run DWARF analyzer for types/sigs",
    "import_pdb": "run PDB analyzer for MS debug symbols",
    "apply_fid_signatures": "Function ID library/runtime naming",
    "propose_struct_from_accesses": "infer struct from pointer accesses",
    "list_open_programs": "all open programs (name, active, sha256)",
    "select_program": "switch active program by name/sha256",
    "set_variables": "atomic name + prototype + locals on one function",
    "apply_naming_convention": "batch-normalize names (dry-run by default)",
    "find_function_by_string": "string xref to function entry + signature",
    "export_offsets": "name+RVA skeleton (tsv/cpp)",
    "analyze_program": "run/re-run Ghidra auto-analysis",
    "list_analyzers": "analyzer names + on/off state",
    "set_analysis_option": "toggle an analyzer before analysis",
    "apply_data_type": "lay a type at an address",
    "batch_apply_data_type": "apply many types, one transaction",
    "create_function": "disassemble + create function at address",
    "propagate_function_types": "commit decompiler-inferred types/names",
    "struct_field": "set/delete struct field at offset",
    "search_tools": "keyword-search this server's tool catalog",
    "get_tool_schema": "full JSON input schema for one tool",
}


def main() -> None:
    names = catalog_names()
    assigned: list[str] = [t for tools in CATEGORIES.values() for t in tools]
    missing = set(names) - set(assigned)
    extra = set(assigned) - set(names)
    dups = sorted({t for t in assigned if assigned.count(t) > 1})
    if missing or extra or dups:
        raise SystemExit(f"category mismatch missing={sorted(missing)} extra={sorted(extra)} dups={dups}")
    for t in names:
        if t not in PURPOSES:
            raise SystemExit(f"missing purpose for {t}")

    n = len(names)
    out: list[str] = [
        "## Tools",
        "",
        f"**{n} tools total.**",
        "",
        "Common conventions on most paginated read tools:",
        "",
        "- **fmt** — `tsv` (default), `csv`, `json`, or `verbose`",
        "- **offset** / **limit** — pagination",
        "- **program** — open program name or sha256 (otherwise the active program)",
        "",
    ]
    for cat, tools in CATEGORIES.items():
        out.append("<details>")
        out.append(f"<summary><b>{cat}</b> ({len(tools)})</summary>")
        out.append("")
        out.append("| tool | purpose |")
        out.append("| --- | --- |")
        for t in tools:
            out.append(f"| `{t}` | {PURPOSES[t]} |")
        out.append("")
        out.append("</details>")
        out.append("")

    out.append(
        "> Live attach and Lua helpers are powerful. They require an attached process "
        "and, for `lua_exec`, target-specific function addresses when built-in example defaults do not match."
    )
    out.append("")

    section = "\n".join(out)
    readme = README.read_text(encoding="utf-8")
    start = readme.index("## Tools")
    end = readme.index("\n## Prompts")
    README.write_text(readme[:start] + section + "\n" + readme[end + 1 :], encoding="utf-8", newline="\n")
    print(f"rewrote Tools section ({n} tools)")


if __name__ == "__main__":
    main()
